# Generated by Django 5.2.8 on 2025-12-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.IntegerField(choices=[(1, 'Like'), (0, 'Dislike')], default=1),
        ),
    ]
