# Generated by Django 5.2.8 on 2025-12-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
    ]
