# Generated by Django 5.2.8 on 2025-12-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='text',
        ),
    ]
